### ISSUE TITLE
Reflect label as a state attribute

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#186]
- Add a test
- Add to documentation
- Update analysis.json

This fix is need by some Lumo selectors. For example: https://github.com/vaadin/vaadin-text-field/blob/master/theme/lumo/vaadin-text-field.html#L51

**Comment by web-padawan** [comment]
Note: when reflecting to attribute, we should take into account two points:

1. The value can be empty string (it actually is by default) and this breaks the height:

![screen shot 2018-01-16 at 16 16 24](https://user-images.githubusercontent.com/10589913/34993309-a1053706-fad8-11e7-9e3f-57743062c0fe.png)

2. After I remove the `value: ''`, the layout is still broken and looks like this: https://github.com/vaadin/vaadin-text-field/blob/master/theme/lumo/vaadin-text-field.html#L46

![screen shot 2018-01-16 at 16 13 43](https://user-images.githubusercontent.com/10589913/34993321-a67ee09c-fad8-11e7-8829-516c99188506.png)

Removing that line above seems to help. @jouni WDYT?

**Comment by jouni** [comment]
The second option is the correct one, IMO, since that makes sure the `label` attribute does not appear on the host when there is no label. 

To fix the alignment, I think we need to use a computed binding for the label element content, e.g. `<label>[[_computeLabel(label)]]</label>`. Polymer serializes an `undefined` value to a white space character, which messes up the baseline alignment.

**Comment by jouni** [comment]
Sorry, I didn’t actually read the issue properly. So, an empty string label still produces a problem.

Can we hide the label element when it’s `:empty`?

**Comment by web-padawan** [comment]
The problem is about applying `:empty` style (the computed function you suggested above does not trigger on the undefined state). Of course we can set label to `value: null` by default instead of the empty string.

**Comment by tomivirkki** [comment]
Instead of reflecting, we could toggle it manually with set/removeAttribute

**Comment by web-padawan** [comment]
I think that I found the right workaround, actually. We should check for empty string attribute explicitly in order to keep proper align:
```css
      :host([label]:not([label=""]))::before {
        /* Label height + input-field margin-top */
        margin-top: calc(var(--lumo-font-size-s) + var(--lumo-space-xs) * 2);
      }

      :host([label]:not([label=""])) {
        margin-top: var(--lumo-space-m);
      }
```
