### ISSUE TITLE
do not assume the default box sizing model (content-box) for prefix icons

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-text-field#199]
When using the `<vaadin-text-field>` element with a prefix icon, as a developer, I expect it to look the same way regardless of the box sizing model set for all elements on the page. Currently with the Lumo theme the prefix icon would display incorrectly if there is a global reset of the box sizing model to 'border-box' (which is one of the commonly used CSS resets).

<img width="944" alt="image" src="https://user-images.githubusercontent.com/22416150/36098733-bbef30fe-1008-11e8-99ff-4cf926c1948a.png">

JS fiddle showing the issue: https://jsfiddle.net/27ps74ao/1/

The CSS rule that seems to be causing the issue:
```css
/* Vaadin icons are based on a 16x16 grid (unlike Lumo and Material icons with 24x24), so they look too big by default */

[part="input-field"] ::slotted(iron-icon[icon^="vaadin:"]) {
  width: calc(var(--lumo-icon-size-m) - 0.5em);
  height: calc(var(--lumo-icon-size-m) - 0.5em);
  padding: 0.25em;
}
```
